

//Home
export const RECEIVED_USER_MARKETS = "GET_USER_MARKETS"
export const FETCHING_USER_MARKETS = "FETCHING_USER_MARKETS"
export const ERROR_FETCHING_USER_MARKETS = "ERROR_FETCHING_USER_MARKETS"
//Find
export const RECEIVED_ADS = "GET_ADS"
export const RECEIVED_HOT_ISSUES = "GET_HOT_ISSUES"
export const RECEIVED_FRESH_ISSUES = "GET_FRESH_ISSUES"
export const RECEIVED_RECOMMENDED_MARKETS = "GET_RECOMMENDED_MARKETS"
export const RECEIVED_RECOMMENDED_SPONSOR = "GET_RECOMMENDED_SPONSOR"

//Mine